management:
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://127.0.0.1:4318/v1/traces}
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.1}

logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        environment: ${DEPLOYMENT_ENVIRONMENT}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
